hello-world:
    message: Hello from production, %s!

management:
  health:
    diskspace:
      enabled: false

info:
  build:
    name: ${name}
    version: ${jar.version}

spring:
  main:
    banner-mode: "off"