server:
  port: 8080

management:
  port: 8081
#  address: 127.0.0.1

hello-world:
    message: Hello, %s!

info:
  build:
    name: spring-boot-service-dev
    description: default description
    version: 0.0.1-LOCAL